/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package INTERFAZ;

import clases.ArchiSeccion;

/**
 *
 * @author Sony Vaio
 */
public class DialogNuevaEscuela extends javax.swing.JDialog {

    private ArchiSeccion archi;

    /**
     * Creates new form DialogNuevaEscuela
     */

    public DialogNuevaEscuela(java.awt.Frame parent, ArchiSeccion archi) {
        super(parent, "REGISTRAR NUEVA ESCUELA DEPORTIVA", true);
        this.archi = archi;
        initComponents();
        setSize(900, 700);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogNuevaEscuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogNuevaEscuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogNuevaEscuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogNuevaEscuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogNuevaEscuela dialog = new DialogNuevaEscuela(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
private void guardarTodo() {
        try {
            // 1. Escuela
            EscuelaDeportiva escuela = new EscuelaDeportiva();
            escuela.setNombre(txtNombreEscuela.getText());
            escuela.setDescripcion(txtDescripcion.getText());

            // 2. Disciplina
            Disciplina d = new Disciplina();
            d.setNombre(txtNombreDisciplina.getText());
            d.setCategoria(txtCategoria.getText());
            d.setCupoMax(Integer.parseInt(txtCupo.getText()));

            // 3. Entrenador
            Entrenador e = new Entrenador();
            e.setNombre(txtNombreEntrenador.getText());
            e.setEspecialidad(txtEspecialidad.getText());
            e.setAniosExp(Integer.parseInt(txtAniosExp.getText()));
            d.setE(e);

            // 4. Horario
            Horario h = new Horario();
            h.setDia(txtDia.getText());
            h.setHoraInicio(txtHoraInicio.getText());
            h.setHoraFin(txtHoraFin.getText());
            d.setH(h);

            // 5. Asignar disciplina a la escuela
            escuela.setD(d);

            // 6. Guardar en archivo
            archi.adicionarEscuelaDirecto(escuela); // método que vamos a crear

            JOptionPane.showMessageDialog(this, "ESCUELA REGISTRADA CON ÉXITO!", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
