/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFAZ;

import clases.ArchiSeccion;
import clases.SeccionDeportes;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Sony Vaio
 */
public class MENUBAR extends javax.swing.JFrame {
    private ArchiSeccion archi;

    /**
     * Creates new form MENUBAR
     */
    public MENUBAR() {
        initComponents();

        archi = new ArchiSeccion("seccion_deportes.dat");
        setTitle("SISTEMA DE GESTION DEPORTIVA - UMSA 2025");
        // Si ya existe archivo, desactivamos el botón crear
        if (new java.io.File("seccion_deportes.dat").exists()) {
            crearArchiBTN.setEnabled(false);
            crearArchiBTN.setText("ARCHIVO YA EXISTE");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        JTPmenu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomSeccionTxt = new javax.swing.JTextField();
        regSeccionBTN = new javax.swing.JButton();
        crearArchiBTN = new javax.swing.JButton();
        fondoS = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        regEscuelaBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomSeccionTxt1 = new javax.swing.JTextField();
        fondoE = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        fondoI = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        fondoA = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        fondoR = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTPmenu.setPreferredSize(new java.awt.Dimension(620, 461));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SECCION DESPORTES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 490, 70));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setText("NOMBRE SECCION:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        nomSeccionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomSeccionTxtActionPerformed(evt);
            }
        });
        jPanel1.add(nomSeccionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 160, 30));

        regSeccionBTN.setBackground(new java.awt.Color(255, 0, 51));
        regSeccionBTN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        regSeccionBTN.setText("REGISTRAR SECCION");
        regSeccionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regSeccionBTNActionPerformed(evt);
            }
        });
        jPanel1.add(regSeccionBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 270, 60));

        crearArchiBTN.setBackground(new java.awt.Color(255, 0, 51));
        crearArchiBTN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        crearArchiBTN.setText("CREAR ARCHIVO");
        crearArchiBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearArchiBTNActionPerformed(evt);
            }
        });
        jPanel1.add(crearArchiBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 260, 60));

        fondoS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fSeccion2.jpg"))); // NOI18N
        jPanel1.add(fondoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JTPmenu.addTab("SECCION", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ESCUELAS DEPORTIVAS");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 490, 70));

        regEscuelaBTN.setBackground(new java.awt.Color(255, 0, 51));
        regEscuelaBTN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        regEscuelaBTN.setText("REGISTRAR NUEVA ESCUELA");
        regEscuelaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEscuelaBTNActionPerformed(evt);
            }
        });
        jPanel2.add(regEscuelaBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 330, 60));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("HAY \"AQUI AGREGAR EL NRO DE ESCUELAS QUE HAY DISPONIBLE\" ESCUELAS DISPONIBLES PARA REGISTRAR");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 740, 50));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("NOMBRE ESCUELA:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 270, -1));

        nomSeccionTxt1.setForeground(new java.awt.Color(0, 255, 255));
        nomSeccionTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomSeccionTxt1ActionPerformed(evt);
            }
        });
        jPanel2.add(nomSeccionTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 190, 30));

        fondoE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoE.jpg"))); // NOI18N
        jPanel2.add(fondoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JTPmenu.addTab("ESCUELAS", jPanel2);

        fondoI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fInscripcion2.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JTPmenu.addTab("INSCRIPCION", jPanel3);

        fondoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fAsistencia.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JTPmenu.addTab("ASISTENCIA", jPanel4);

        fondoR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoReporte.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JTPmenu.addTab("REPORTE", jPanel5);

        getContentPane().add(JTPmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, 758, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA DE GESTION DEPORTIVA - UMSA 2025");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 764, 37));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomSeccionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomSeccionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomSeccionTxtActionPerformed

    private void regSeccionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regSeccionBTNActionPerformed
        String nombre = nomSeccionTxt.getText().trim();
        
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escribe el nombre de la seccion", 
                "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        archi.registrarSeccion(nombre);
        
        JOptionPane.showMessageDialog(this, 
            "SECCION '" + nombre.toUpperCase() + "' REGISTRADA!", 
            "CON EXITO", JOptionPane.INFORMATION_MESSAGE);
        
        // Desactiva para que no lo haga dos veces
        regSeccionBTN.setEnabled(false);
        nomSeccionTxt.setEnabled(false);
        crearArchiBTN.setEnabled(false);
        limpiarSeccion();

    }//GEN-LAST:event_regSeccionBTNActionPerformed

    private void crearArchiBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearArchiBTNActionPerformed
        // CREAR EL ARCHIVO
        archi.crear();
        JOptionPane.showMessageDialog(this, "Archivo creado correctamente!",
                "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_crearArchiBTNActionPerformed

    private void regEscuelaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEscuelaBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regEscuelaBTNActionPerformed

    private void nomSeccionTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomSeccionTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomSeccionTxt1ActionPerformed
    public void limpiarSeccion() {
        nomSeccionTxt.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENUBAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENUBAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENUBAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENUBAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENUBAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTPmenu;
    private javax.swing.JButton crearArchiBTN;
    private javax.swing.JLabel fondoA;
    private javax.swing.JLabel fondoE;
    private javax.swing.JLabel fondoI;
    private javax.swing.JLabel fondoR;
    private javax.swing.JLabel fondoS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nomSeccionTxt;
    private javax.swing.JTextField nomSeccionTxt1;
    private javax.swing.JButton regEscuelaBTN;
    private javax.swing.JButton regSeccionBTN;
    // End of variables declaration//GEN-END:variables
}
